package com.accenture.lambda.service.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

@JsonIgnoreProperties(ignoreUnknown = true)
public record Attributes(
        @JsonProperty("ResultID") Integer resultId,
        @JsonProperty("Loc_name") @NotNull String locName,
        @JsonProperty("Status") String status,
        @JsonProperty("Score") BigDecimal score,
        @JsonProperty("Match_addr") String matchAddress,
        @JsonProperty("LongLabel") String longLabel,
        @JsonProperty("ShortLabel") String shortLabel,
        @JsonProperty("Addr_type") String addressType,
        @JsonProperty("Type") String type,
        @JsonProperty("PlaceName") String placeName,
        @JsonProperty("Place_addr") String placeAddress,
        @JsonProperty("Phone") String phone,
        @JsonProperty("URL") String url,
        @JsonProperty("Rank") Integer rank,
        @JsonProperty("AddBldg") String addBuilding,
        @JsonProperty("AddNum") String addNumber,
        @JsonProperty("AddNumFrom") String addNumberFrom,
        @JsonProperty("AddNumTo") String addNumberTo,
        @JsonProperty("AddRange") String addRange,
        @JsonProperty("Side") String side,
        @JsonProperty("StPreDir") String streetPreDir,
        @JsonProperty("StPreType") String streetPreType,
        @JsonProperty("StName") String streetName,
        @JsonProperty("StType") String streetType,
        @JsonProperty("StDir") String streetDirection,
        @JsonProperty("BldgType") String buildingType,
        @JsonProperty("BldgName") String buildingName,
        @JsonProperty("LevelType") String levelType,
        @JsonProperty("LevelName") String levelName,
        @JsonProperty("UnitType") String unitType,
        @JsonProperty("UnitName") String unitName,
        @JsonProperty("SubAddr") String subAddress,
        @JsonProperty("StAddr") String streetAddress,
        @JsonProperty("Block") String block,
        @JsonProperty("Sector") String sector,
        @JsonProperty("Nbrhd") String neighbourhood,
        @JsonProperty("District") String district,
        @JsonProperty("City") String city,
        @JsonProperty("MetroArea") String metroArea,
        @JsonProperty("Subregion") String subRegion,
        @JsonProperty("Region") String region,
        @JsonProperty("RegionAbbr") String regionAbbreviation,
        @JsonProperty("Territory") String territory,
        @JsonProperty("Zone") String zone,
        @JsonProperty("Postal") String postal,
        @JsonProperty("PostalExt") String postalExtension,
        @JsonProperty("Country") String country,
        @JsonProperty("CntryName") String countryName,
        @JsonProperty("LangCode") String languageCode,
        @JsonProperty("Distance") Integer distance,
        @JsonProperty("X") Double x,
        @JsonProperty("Y") Double y,
        @JsonProperty("DisplayX") Double displayX,
        @JsonProperty("DisplayY") Double displayY,
        @JsonProperty("Xmin") Double xMin,
        @JsonProperty("Xmax") Double xMax,
        @JsonProperty("Ymin") Double yMin,
        @JsonProperty("Ymax") Double yMax,
        @JsonProperty("ExInfo") String exInfo,
        @JsonProperty("UPRN") @JsonSetter(nulls = Nulls.AS_EMPTY) String uprn,
        @JsonProperty("UDPRN") String udprn,
        @JsonProperty("Classification") @JsonSetter(nulls = Nulls.AS_EMPTY) String classification,
        @JsonProperty("OfficialRMAddress") String officialRmAddress,
        @JsonProperty("BlpuState") Integer blpuState,
        @JsonProperty("BlpuStateDate") String blpuStateDate,
        @JsonProperty("LocalCustodianCode") Integer localCustodianCode,
        @JsonProperty("AddressBasePostal") String addressBasePostal,
        @JsonProperty("MultiOccCount") Integer multipleOccupancyCount,
        @JsonProperty("ParentUPRN") @JsonSetter(nulls = Nulls.AS_EMPTY) String parentUprn,
        @JsonProperty("TownName") String townName,
        @JsonProperty("Postcode") String postcode,
        @JsonProperty("HouseNumber") String houseNumber,
        @JsonProperty("StreetDescription") String streetDescription,
        @JsonProperty("SubBuildingType") String subBuildingType,
        @JsonProperty("SubBuildingName") String subBuildingName,
        @JsonProperty("PropertyName") String propertyName,
        @JsonProperty("OfficialAddress") String officialAddress,
        @JsonProperty("PAONumber") String paoNumber,
        @JsonProperty("PAOText") String paoText,
        @JsonProperty("USRN") String usrn,
        @JsonProperty("BLPULogicalStatus") Integer blpuLogicalStatus,
        @JsonProperty("LPILogicalStatus") Integer lpiLogicalStatus,
        @JsonProperty("BuildingUnit") String buildingUnit) {}
